/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/core/useGLTF'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'
import { a, useSpring } from '@react-spring/three'

type GLTFResult = GLTF & {
  nodes: {
    Plane000: THREE.Mesh
    Plane000_1: THREE.Mesh
    Plane000_2: THREE.Mesh
    Plane000_3: THREE.Mesh
    Plane000_4: THREE.Mesh
    Plane009: THREE.Mesh
    Plane009_1: THREE.Mesh
    Plane009_2: THREE.Mesh
    Plane009_3: THREE.Mesh
    Plane009_4: THREE.Mesh
  }
  materials: {
    Main: THREE.MeshStandardMaterial
    Accent: THREE.MeshStandardMaterial
    DarkAccent: THREE.MeshStandardMaterial
    DarkGrey: THREE.MeshStandardMaterial
    Black: THREE.MeshStandardMaterial
  }
}

export default function DoubleDoor({isOpen, ...props}: JSX.IntrinsicElements['group'] & {
    isOpen: boolean,
}) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/models/spaceship/Door_Double.glb') as GLTFResult



    const { spring } = useSpring({
        spring: isOpen ? 1 : 0,
        config: { mass: 5, tension: 300, friction: 100, precision: 0.0001 },
    })

    const offset = spring.to([0, 1], [0, 1.25])
    const offset2 = spring.to([0, 1], [0, -1.25])

  return (
    <group ref={group} {...props} dispose={null}>
        <a.group position-x={offset}>
          <mesh material={materials.Main} geometry={nodes.Plane000.geometry} castShadow receiveShadow />
          <mesh material={materials.Accent} geometry={nodes.Plane000_1.geometry} castShadow receiveShadow />
          <mesh material={materials.DarkAccent} geometry={nodes.Plane000_2.geometry} castShadow receiveShadow />
          <mesh material={materials.DarkGrey} geometry={nodes.Plane000_3.geometry} castShadow receiveShadow />
          <mesh material={materials.Black} geometry={nodes.Plane000_4.geometry} castShadow receiveShadow />
        </a.group>
        <a.group position-x={offset2}>
          <mesh material={materials.Main} geometry={nodes.Plane009.geometry} castShadow receiveShadow />
          <mesh material={materials.Accent} geometry={nodes.Plane009_1.geometry} castShadow receiveShadow />
          <mesh material={materials.DarkAccent} geometry={nodes.Plane009_2.geometry} castShadow receiveShadow />
          <mesh material={materials.DarkGrey} geometry={nodes.Plane009_3.geometry} castShadow receiveShadow />
          <mesh material={materials.Black} geometry={nodes.Plane009_4.geometry} castShadow receiveShadow />
        </a.group>
    </group>
  )
}

useGLTF.preload('/models/spaceship/Door_Double.glb')
